### PR TITLE
fix: log-level being ignored

### LINKED ISSUE #1197: bug: --log-level flag appears to be ignored
### Problem
The `--log-level` flag does nothing for `wakunode2`:
```
 # ./wakunode2 --help | grep log-level
 --log-level               Sets the log level. [=LogLevel.INFO].
 # systemctl cat nwaku | grep log
  --log-level=info \
 # journalctl -o cat -au nwaku | grep DBG | wc -l
612
```

### Impact
What's the point of defining a flag that does nothing?

### PR DESCRIPTION
**Pull request by alrevuelta**
Closes #1197 

Problem:
* Without `-d:chronicles_runtime_filtering:on` flag `setLogLevel` does not work.
* `setLogLevel` only works with levels less verbose than `-d:chronicles_log_level=xxx`, i.e. `setLogLevel(TRACE)` won't work if `-d:chronicles_log_level=INFO`.
* More info [here](https://github.com/status-im/nwaku/issues/1197#issuecomment-1271489622).

Solution:
* Add `-d:chronicles_runtime_filtering:on` when compiling all binaries
* Set `-d:chronicles_log_level=TRACE` to all nwaku `app` and `wakunode2`

Now the following works as expected. Note that default is `INFO`.

```
$ ./build/wakunode2 --log-level=TRACE
$ ./build/wakunode2 --log-level=DEBUG
$ ./build/wakunode2 --log-level=WARN
```

### CODE REVIEW

**Review by LNSD — APPROVED** [review]
LGTM ✅

**Review by jakubgs — APPROVED** [review]
Thanks.

**Review by jm-clius — APPROVED** [review]
LGTM. One thing to consider is that the default log level almost everywhere will now be `INFO`, whereas previously it would have been `DEBUG` after compilation. We may want to change the default for fleet deployments to `DEBUG` so that we can continue using it as before: https://github.com/status-im/infra-role-nim-waku/blob/master/defaults/main.yml#L19

**Comment by jakubgs** [comment]
@jm-clius actually we already explicitly set log level to `info`:
```
 > a all -a 'grep log-level /docker/nim-waku/docker-compose.yml'
node-01.do-ams3.wakuv2.prod | CHANGED | rc=0 >>
      --log-level=info
node-01.gc-us-central1-a.wakuv2.prod | CHANGED | rc=0 >>
      --log-level=info
node-01.ac-cn-hongkong-c.wakuv2.prod | CHANGED | rc=0 >>
      --log-level=info
```
```
node-01.do-ams3.wakuv2.test | CHANGED | rc=0 >>
      --log-level=info
node-01.gc-us-central1-a.wakuv2.test | CHANGED | rc=0 >>
      --log-level=info
node-01.ac-cn-hongkong-c.wakuv2.test | CHANGED | rc=0 >>
      --log-level=info
```
```
node-01.do-ams3.status.test | CHANGED | rc=0 >>
      --log-level=info
node-01.gc-us-central1-a.status.test | CHANGED | rc=0 >>
      --log-level=info
node-01.ac-cn-hongkong-c.status.test | CHANGED | rc=0 >>
      --log-level=info
```
But we can always change that.

**Comment by jm-clius** [comment]
> actually we already explicitly set log level to `info`:

Yeah, indeed (`info` explicitly set for fleet deployments and it's now the default for everyone running nodes without explicit configuration). Since we're using logging quite extensively for debugging on the fleets, we should change the log level to `DEBUG`. Other node operators may also expect `debug` level logs, so we'll have to inform them that default behaviour has changed.

**Comment by jakubgs** [comment]
Okay, done:

- https://github.com/status-im/infra-status/commit/13aa35f1 - status: change log level to debug
- https://github.com/status-im/infra-nim-waku/commit/015f41c1 - wakuv2.test/prod: change log level to debug

**Pull request merged**
