### PR TITLE
chore: update submodules

### PR DESCRIPTION
**Pull request by jm-clius**
Updates submodules.

Main focus is to include at least two fixes related to websockets:
- Setting activity flag to prevent websocket connections timing out: https://github.com/status-im/nim-libp2p/commit/1696d0c7077fc1d4bec740546a296b3d400f1375
- Several improvements/fixes in nim-websock: https://github.com/status-im/nim-websock/commits/main

Some fixes were required for compatibility with underlying changes in the `PeerStore`. This is still a workaround until we prioritise work to replace our own `WakuPeerStore` with the underlying libp2p `PeerStore` as set out in https://github.com/status-im/nwaku/issues/622

### CODE REVIEW

**Comment by LNSD** [comment]
I have one question about #622, do we want to re-prioritize it so we tackle it as part of one of the coming releases?

**Comment by jm-clius** [comment]
> I have one question about #622, @jm-clius, do we want to re-prioritize it so we tackle it as part of one of the coming releases?

It is currently associated with the milestone for v0.11 (mid-August). Do you mean that we should include it in the upcoming release? I think we'd like to keep the scope for v0.10 minimal so we can deliver it in time.

**Comment by LNSD** [comment]
> > I have one question about #622, @jm-clius, do we want to re-prioritize it so we tackle it as part of one of the coming releases?
> 
> It is currently associated with the milestone for v0.11 (mid-August). Do you mean that we should include it in the upcoming release? I think we'd like to keep the scope for v0.10 minimal so we can deliver it in time.

Oh, my bad 🙏🏼 I saw it in the "icebox", but I did not see it as part of the 0.11 milestone. Aug release makes sense, so we do not add unnecessary risk to v0.10 😁

**Review by kaiserd — APPROVED** [review]
LGTM!

**Pull request merged**
