### PR TITLE
chore(docker): use NIMFLAGS instead of NIM_PARAMS

### PR DESCRIPTION
**Pull request by kaiserd**
This PR addresses #925.
Also enables the `d5waku` protocol ID for discv5 on fleets without additional config.

### CODE REVIEW

**Comment by jakubgs** [comment]
This was built in https://ci.status.im/job/nim-waku/job/deploy-status-test/9/ and I deplyed it on `node-01.do-ams3.wakuv2.test` but:
```
INF 2022-05-11 21:36:27.177+00:00 WakuRLNRelay is enabled                    topics="wakunode.setup" tid=1 file=wakunode2.nim:1196
DBG 2022-05-11 21:36:27.177+00:00 rln-relay membership index                 topics="wakurlnrelayutils" tid=1 file=waku_rln_relay_utils.nim:328 rlnRelayMemIndex=0
/app/waku/v2/node/wakunode2.nim(1341) wakunode2
/app/waku/v2/node/wakunode2.nim(1204) setupProtocols
/app/waku/v2/node/wakunode2.nim(541) mountRlnRelay
/app/vendor/nim-chronos/chronos/asyncfutures2.nim(365) futureContinue
/app/waku/v2/node/wakunode2.nim(603) mountRlnRelay
/app/waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim(44) createRLNInstance
/app/vendor/nimbus-build-system/vendor/Nim/lib/system/io.nim(693) readFile
[[reraised from:
/app/waku/v2/node/wakunode2.nim(1341) wakunode2
/app/waku/v2/node/wakunode2.nim(1204) setupProtocols
]]
Error: unhandled exception: cannot open: waku/v2/protocol/waku_rln_relay/parameters.key [IOError]
```
Seems broken.

**Comment by kaiserd** [comment]
Ill address the RLN part tomorrow. Thanks for the help!

**Comment by kaiserd** [comment]
I think I fixed the issue. Still have to test it.
Here is a rough description (I can provide more detail if desired):

The file pointed to by the error message
`waku/v2/protocol/waku_rln_relay/parameters.key` was not copied into the container.
I did not consider this to be the issue, because without this PR the image seemed to work.
However, with overriding `NIM_PARAMS`, `-d:rln` was not set even with `RLN=true`.
`RLN=true` would normally trigger `-d:rln` to be set, but not when overriding `NIM_PARAMS` from outside (as happened here).
So, the rln code requiring this file was never executed, which silently seemed to work.

cc @staheri14

**Comment by kaiserd** [comment]
I also added `RLN=true` to the deps make rule call, because `RLN=true` triggers options there, too, which also can be cached.

**Review by jakubgs — APPROVED** [review]
Nice, I tested the image on one host and it appears to work fine:
```
admin@node-01.do-ams3.wakuv2.test:/docker/nim-waku-v2 % d
CONTAINER ID   NAMES         IMAGE                                                 CREATED         STATUS
3dcf250e65e8   websockify    statusteam/websockify:v0.10.0                         2 minutes ago   Up 2 minutes
d0a9f7f2cfce   nim-waku-v2   statusteam/nim-waku:deploy-status-test-nimflag-test   2 minutes ago   Up 2 minutes (healthy)
```
Well done.

**Comment by kaiserd** [comment]
Thank you very much @jakubgs !

**Comment by staheri14** [comment]
@kaiserd thanks for resolving the issue! it might also explain why despite mounting the waku-rln-relay protocol on the test fleets, the interaction was showing otherwise.

**Comment by kaiserd** [comment]
@staheri14 Yes :). RLN should work properly on the fleet nodes after this PR gets deployed. In my local tests, the RLN protocol was mounted after applying these changes, but without, it was not mounted becasue `-d:rln` was not set.

**Comment by staheri14** [comment]
@kaiserd curious to know whether it was finally needed to use the `override` directive for the `NIM_PARAMS` of the Makefile?

**Comment by kaiserd** [comment]
@staheri14 
> @kaiserd curious to know whether it was finally needed to use the override directive for the NIM_PARAMS of the Makefile?

`override` is not needed and this PR does not introduce it, but `override` could be used on `NIM_PARAMS` to enforce that nothing from the outside overrides it.

> Update: I think the answer lies in this comment #925 (comment)?

Yes. With this PR, the Jenkins pipeline uses `NIMFLAGS` instead of `NIM_PARAMS` to add compiler flags. This is now in line with the nimbus build system doc.
This pattern of having a variable for internal use and one for external use makes sense, because make does not allow adding to a variable from outside the Makefile.

**Review by jm-clius — APPROVED** [review]
Thanks for this, @kaiserd. Will save a lot of future headaches.

**Pull request merged**
