### PR TITLE
chore(chat2): selection of store node at random

### LINKED ISSUE #1110: bug: Store node selection is not random
### Problem
There is an unexpected behavior regarding peer selection in the store protocol (chat2 usecase). While the selcetion is supposed to be at random, the same store node is picked for every run. 

### Impact
Not critical, just good to be investigated. 

### To reproduce
If you can reproduce the behavior, steps to reproduce:
1. Run `make chat2`
2. run `./build/chat2 --fleet:test` this is to fetch historical messages from the test fleets without specifying a certain node address
3. You will see a message similar to this
```
Connecting to test fleet using DNS discovery...
Discovered and connecting to @[16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm, 16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ, 16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS]
Listening on
 /ip4/75.157.120.249/tcp/60000/p2p/16Uiu2HAmEHC7NGTqhc5ugpneGjkmWgxySrmEHvwUxSmnSVJYz3Eg
Store enabled, but no store nodes configured. Choosing one at random from discovered peers
Connecting to storenode: 16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm
```
5. run another chat2 following step 2 and you will see the same node address is shown as the selected store node
```
Connecting to test fleet using DNS discovery...
Discovered and connecting to @[16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm, 16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ, 16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS]
Listening on
 /ip4/75.157.120.249/tcp/60000/p2p/16Uiu2HAm3qU2ym3FApmp474L1M5xfMYvfHkBJgCPy8Tisw4p75cY
Store enabled, but no store nodes configured. Choosing one at random from discovered peers
Connecting to storenode: 16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm
```
As you can see, 3 distinct nodes are discovered but each time the same node is selected as the storenode i.e., `16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm`.

### Expected behavior
The expected behavior is that to see a different store node for each run (or across multiple different runs).  

### Screenshots/logs
NA

### nwaku version/commit hash

`v0.11-14-gecf4ba`

### Additional context
This behavior was reported as part of rln testnet1. https://github.com/status-im/nwaku/issues/1069

### PR DESCRIPTION
**Pull request by rymnc**
Should resolve #1110

### CODE REVIEW

**Review by LNSD — APPROVED** [review]
LGTM ✅

**Comment by LNSD** [comment]
@rymnc Note that the `chat2` example is not covered by our tests. Therefore some manual testing is needed.

**Comment by rymnc** [comment]
Here's a screenshot -
image

Does anyone know what these bytes are? (after the connection to the store node)

```
�ma�8yPqR�&Ce�&f�Xd��(�������/ݥ�9��ENN�.�&ߧ(���E�o[�~oDI�-;�o�4�|�aQ�{�(e�!��y6VR,�����i��"�d�C��{�A� ��֟�h|��#V�{M��n��Ԥ�q �E�-i
                                                                                                                                �(e�� �Ί0+�{��^2��	��$�J�)��6,��wqQ�s�
                                                                                                                                                                           @�a�Ef�e�\�����Q�v1�N��������tgxg���Gk�Թ����E��H�h,�`���̖B�9�P�ӌo��[�
�  �ˇ՘�
G���3қۃ� ��-k��wĝS�ۆx���2h��ۅ�%^�
�����

~�=�������E'�ӎ�9w�H�k1�C��U��|�}z�
�@EctӀ>��"�C�:���Qb�;�s���,��)���%)ʨ��g�?%Ӌ��x�T=(�<)��W��M���ÿ��V� ;ҮCڀ����
H?�%�72Xm�u�Q��Lq~����qs��K��̌��>���T~��}8!4��cO�D9s�4s&^CT�me0+F&Q�����T���  ���d��}ATݿz!l�_&�N���\�y�߂i��]�qG�ԃ?vK�T�֊�b
XY�/߰
|�ᤏt_�~�n/'�Tì��� ]0���;�\O�)��|bm�d&�����ĕ�I��dD�S�ҭ�XX��/��zf�\E:o���'&~��V�i�?���^��q�����j��-|���
                                                                                                     ����R)Q�
� ��Y�8��-��R�F:�����xܝ�q(flQ�
�;9Y1?Kt,�4�!T����v�5�[tS���N=\p��`NK�2��w">{���))�֡�!
                                                      wͯ��,̝�l���q]��g4���i���� �����˟tj���Q�|�n��
l��1�a��b�oT>$
               �I/��p���Ϩd ^<lL�
�B�ݙ~��S/oƘ�Wuc�K���l�Q;�=��ȹ�!AE^����&�b�)��t��t @c8U\lP��q�~�e�+
$]�?�
��#�?$9:Ƨ���,e:Kz���Ls?,��H:*�o�@�n�d�My���ԗ�nM'��2Q�ȟ���g*�~�C��YY��i3���z�`�6�N�p�񛰋�7�~����(��lO�~Ϩ�w�Bm"��G����j�w�R��"���Ĥ.<e4�;����8D��B����(�C¤o�V�?��s;ʗ�^b���"X�.B
wė/Y�rCn�Q7��(8�;��ҭ���94�r���lW�
                                 ��;�1��(�W�U�H���!.@�¸�A+A�&
���]�s�F�
M�יq�gp���Y�x���@�V4yl��z@�o����=ޚ�i�{����t-�ޠ*A�ZG6L�b���B����T�M	��:�{*�V���^A��W0������g4��h$��(�3s��C����q1���2
��o�U�9~�j����ӡn�����QϷ�4O6([�_Lh�o1�����Q#1���G�
D�=������gJS��d�PH{.��������+��V����MC
�ʊ�����?�/�
           ~t^PDg`\��ᤴ�Ya,B99i��*��p̆
+5L�                                �~�׫�
    ce��+��_�=�3��;��q��&�
                          �~�٘q�azvbM�����ʖP.N*]ܬ�wGD^X͠kH;?
                                                          ��<��ɷ]���R�0�Z:#qbkUvR�1C4��Z�y��a��EiRp1�
                                                                                                     H���A[5H�a�
z٭A�a����                                                                                                       :��<���Q&��g��Z�/R,Lz3$	��$c��1��P�*
rj�뿹oU0��Y	�	n
`�Z6$��n���{�A�^T�K	���[�#cammCCnR
�`��C%�Y$�(+��&�Hi�I!��Cb?�y��m&-B؍��I5�?KlU8m}�
                                                 �xeȾ��H��0*�)��Fw�L���ҡ���vF	�{UF;�����1_�p�,Dd���0��=q����ᅒW��M�B5���ג�
                                                                                                                            �����n+�I����S���+JA�V~�<Z�ĩ]
���|�9£����wn&�o�Fʔ`7�_�+Њk�%7KB4)�Xl�6���Gs�#�Ʈ�n$0��4�D;����`r��j+��iA�                                                                              m�{Zv�9̒;O���I�T�Pp�f�,�9U��ѿ#L�ـ�#E^�U�ډq
```

**Review by jm-clius — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
