### PR TITLE
chore: more regular keepalive pings

### PR DESCRIPTION
**Pull request by jm-clius**
Minimal PR to lower the period between keepalive `PING`s from `5.min` to `2.min`.

### Why?

Libp2p TCP connections have an underlying timeout of `10.min`. The keepalive is meant to prevent these and other timeouts from happening, but once every `5.min` leaves very little room for error (if a node misses one `PING` for some reason it might still trigger a timeout).

Note that we do not necessarily want (or need to) make this period either configurable or dependent on a specific underlying constant (e.g. the TCP timeout), as this is mostly a workaround mechanism for fleet nodes to remain connected during idle periods.

### CODE REVIEW

**Review by LNSD — APPROVED** [review]
LGTM ✅

**Comment by LNSD** [comment]
One related/unrelated question. Is this PING mechanism at "application level" or at "transport level"? Do we have something similar for the WebSocket transport?

**Review by kaiserd — APPROVED** [review]
LGTM :+1:

**Comment by jm-clius** [comment]
> One question: Is this PING mechanism at "application level" or at "transport level"? Do we have something similar for the WebSocket transport?

Ping is a libp2p protocol that can run over any transport, therefore "application level" from this perspective. It therefore works for any transport, including websocket.

**Pull request merged**
