### PR TITLE
chore: remove unused imports

### PR DESCRIPTION
**Pull request by LNSD**
A gardening PR 🌳 cleaning up all the `[UnusedImport]` warnings

### CODE REVIEW

**Review by jm-clius — APPROVED** [review]
Issa lot. 😅 Do we know much yet about why unused import detection seems to be better in the 1.6 compiler? Haven't looked into this yet.

**Review by rymnc — APPROVED** [review]
LGTM!

**Review by alrevuelta — APPROVED** [review]
wow, thanks for this. actually i wouldn't mind if it errors when having unused imports. but based on the compiler flags the closest i find is warningAsError:X:on|off, and that would be too strict imho.

**Comment by LNSD** [comment]
Regarding _Warnings_ in general (not only the `[UnusedImport]` warning). It should be the developer's responsibility to avoid adding more warnings. And it should be a continuous maintenance task.

We should reduce the warnings to the minimum number to avoid [alert fatigue](https://www.atlassian.com/incident-management/on-call/alert-fatigue). With those many warnings, we end up not paying attention to them, which could mask more severe issues.

I took the task this time and did it, but please try to keep the warnings number low.

**Comment by LNSD** [comment]
> Do we know much yet about why unused import detection seems to be better in the 1.6 compiler?

No idea at all 🤷🏼 But it is excellent! Because before the upgrade, I knew that there were modules that were not used, and I had to do the test manually (remove, compile and repeat).

**Pull request merged**
