### PR TITLE
chore: remove unused imports

### PR DESCRIPTION
**Pull request by LNSD**
Remove multiple `UnusedImport` warnings from the codebase:

```bash
/home/lorenzo/code/status/nwaku/waku/v2/protocol/waku_store/waku_store.nim(10, 6) Warning: imported and not used: 'algorithm' [UnusedImport]
/home/lorenzo/code/status/nwaku/waku/v2/utils/wakuswitch.nim(6, 7) Warning: imported and not used: 'byteutils' [UnusedImport]
/home/lorenzo/code/status/nwaku/waku/v2/utils/wakuswitch.nim(4, 6) Warning: imported and not used: 'sequtils' [UnusedImport]
/home/lorenzo/code/status/nwaku/waku/v2/utils/wakuswitch.nim(10, 23) Warning: imported and not used: 'dnsresolver' [UnusedImport]
/home/lorenzo/code/status/nwaku/waku/v2/node/config.nim(11, 3) Warning: imported and not used: 'web3' [UnusedImport]
/home/lorenzo/code/status/nwaku/waku/v2/node/discv5/waku_discv5.nim(4, 6) Warning: imported and not used: 'sequtils' [UnusedImport]
/home/lorenzo/code/status/nwaku/tests/v2/test_wakunode.nim(27, 3) Warning: imported and not used: 'test_helpers' [UnusedImport]
/home/lorenzo/code/status/nwaku/tests/v2/test_wakunode.nim(5, 6) Warning: imported and not used: 'sequtils' [UnusedImport]
/home/lorenzo/code/status/nwaku/tests/v2/test_waku_pagination.nim(3, 6) Warning: imported and not used: 'algorithm' [UnusedImport]
/home/lorenzo/code/status/nwaku/tests/v2/test_waku_pagination.nim(8, 3) Warning: imported and not used: 'test_helpers' [UnusedImport]
/home/lorenzo/code/status/nwaku/tests/v2/test_waku_payload.nim(7, 3) Warning: imported and not used: 'test_helpers' [UnusedImport]
/home/lorenzo/code/status/nwaku/tests/v2/test_jsonrpc_waku.nim(29, 3) Warning: imported and not used: 'test_helpers' [UnusedImport]
/home/lorenzo/code/status/nwaku/tests/v2/test_migration_utils.nim(4, 6) Warning: imported and not used: 'sequtils' [UnusedImport]
/home/lorenzo/code/status/nwaku/tests/v2/test_waku_discv5.nim(4, 6) Warning: imported and not used: 'sequtils' [UnusedImport]
```

### CODE REVIEW

**Review by jm-clius — APPROVED** [review]
Thanks! Overdue.

**Comment by LNSD** [comment]
The CI builds are failing, because when I ran it locally I was not compiling with the `-d:rln` flag enabled. I can reproduce the issue locally with that flag.

**Review by kaiserd — APPROVED** [review]
LGTM :+1:  I also checked the tests locally including `-d:rln` :).

**Comment by LNSD** [comment]
I cleaned out with the latest push some `UnusedImport` warnings that appeared in the CI logs and I missed them before because of the `-d:rln` flag. If the build, pass, we should be good to go 😁

**Comment by LNSD** [comment]
Seems that since almost any binary depends on the `wakunode2.nim` file, it is almost impossible to remove all `UnusedImport` warnings. There's always a binary that requires the import.

Some work is necessary to split all the logic from the `wakunode2.nim` file to avoid this issue and as the cyclic import issues.

**Pull request merged**
