### PR TITLE
feat(Rln relay): Improves rln-chat2 interface, displays links to the registration tx, warns about spam messages

### PR DESCRIPTION
**Pull request by staheri14**
Thie PR is a progress towards https://github.com/status-im/nwaku/issues/1069
Addresses a subset pf comments re "chat interface", namely:
- Warns users when about their spamming activity
- Provides users with a link to their registration tx on Goerli testnet

### CODE REVIEW

**Comment by LNSD** [comment]
I understand that at this moment the goal is to have a prototype where the user is using the command-line. So the comments below are just suggestions 😁 

IMO, writing to the stdout (via echo, or via any other means) should only happen from the main application, the nodewaku2 in our case. 

Can we make the "warning" an event that can be consumed in the future by other APIs (e.g., an android/ios app that wraps the nwaku implementation). In that case, you cannot use the stdout to notify the user. 

So in this case I would create a callback to the "warning event" and hook it in nodewaku2 and call `echo` inside the callback method.

**Review by jm-clius — COMMENTED** [review]
LGTM. Feel free to mark as ready for review when it is. Agree with @LNSD that the `chat2` toy application can do with a cleanup, though this is an effort separate from RLN.

**Comment by staheri14** [comment]
> IMO, writing to the stdout (via echo, or via any other means) should only happen from the main application, the nodewaku2 in our case.
> 
> Can we make the "warning" an event that can be consumed in the future by other APIs (e.g., an android/ios app that wraps the nwaku implementation). In that case, you cannot use the stdout to notify the user.
> 
> So in this case I would create a callback to the "warning event" and hook it in nodewaku2 and call `echo` inside the callback method.

I believe that the current implementation is also event-driven. The `mountRlnRelay` proc accepts a callback function to be triggered when the registration tx gets mined. The callback function is defined and passed by the chat2 user (the main program) and contains the print statement. Do you suggest something different than this?

**Comment by staheri14** [comment]
@jm-clius Thanks, forgot to mark it as ready when added the reviewers. It is now marked as ready!

**Comment by staheri14** [comment]
@LNSD I see, I think your suggestion is about the `publish` proc which prints a warning about spamming. I can also update the interface of that proc to accept a callback function. Already on it.

**Review by LNSD — APPROVED** [review]
LGTM ✅

**Pull request merged**
