### PR TITLE
WIP 35/WAKU2-NOISE Implementation

### PR DESCRIPTION
**Pull request by s1fr0**
WIP Implementation for [35/WAKU2-NOISE](https://rfc.vac.dev/spec/35/).

Main PR:  https://github.com/status-im/nim-waku/issues/881

### CODE REVIEW

**Comment by oskarth** [comment]
Thanks for adding WIP PR! Please add reviewers and mark ready for review once PR is ready.

**Comment by oskarth** [comment]
Thanks for adding WIP PR! Please add reviewers and mark ready for review once PR is ready.

**Comment by staheri14** [comment]
Thanks @s1fr0 for the PR! I had a quick look and your implementation looks fine. 
One general comment about the code documentation, the more comments you put, especially about the functionality of each proc, the easier would be the review process and the more readable the code (I know it is a WIP, so you may already have this in mind, only wanted to re-emphasize).

**Comment by oskarth** [comment]
@s1fr0 Can we break this apart into smaller PRs with the goal of getting partial progress merged today or tomorrow? In general we want to have small, incremental PRs. As long as it doesn't break things and it provides some quantum of utility it is useful.

For example, the basic `noise.nim` stuff, basic data structure additions and the subset of tests that pass, e.g.

**Pull request closed without merging**
